services:
  postgresql:
    container_name: postgresql-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nodejs-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U galih -d app"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
    restart: on-failure
  nodejs:
    container_name: backend-nodejs
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_USER=galih
      - DB_PASSWORD=password
      - DB_HOST=postgresql-db
      - DB_NAME=app
      - DB_PORT=5432
    networks:
      - nodejs-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: on-failure
    depends_on:
      postgresql:
        condition: service_healthy

networks:
  nodejs-network:
    driver: bridge
